// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "API Support",
            "url": "https://github.com/keshavstack/MeshVPN-slef-hosting"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/telemetry/deployment-request": {
            "post": {
                "description": "Records metrics for a single HTTP request to a user deployment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telemetry"
                ],
                "summary": "Record deployment HTTP request metrics",
                "parameters": [
                    {
                        "description": "Request metrics",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.DeploymentRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/telemetry/deployment-request/batch": {
            "post": {
                "description": "Records metrics for multiple HTTP requests to user deployments in a batch",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Telemetry"
                ],
                "summary": "Record multiple deployment HTTP request metrics",
                "parameters": [
                    {
                        "description": "Batch of request metrics",
                        "name": "requests",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.BatchDeploymentRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/whoami": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve authenticated user's information",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Get current user information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.WhoAmIResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deploy": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Queue a new application deployment from a git repository",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Deploy a new application",
                "parameters": [
                    {
                        "description": "Deployment configuration",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/httpapi.DeployRequestPayload"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/httpapi.DeployResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deployments": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get a list of all deployments for the authenticated user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "List all deployments",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.DeploymentListResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deployments/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve complete deployment information including config, metrics, pods, and resources",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Get comprehensive deployment details",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.DeploymentDetails"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deployments/{id}/analytics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get aggregated metrics for a specific deployment (backward compatible)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Get deployment analytics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Deployment analytics with metrics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deployments/{id}/analytics/stream": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Stream real-time metrics updates every 5 seconds via Server-Sent Events",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Analytics"
                ],
                "summary": "Stream live deployment metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JWT token (SSE doesn't support headers)",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "SSE stream",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deployments/{id}/app-logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve runtime logs for a specific deployment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Get application runtime logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 200,
                        "description": "Number of log lines to retrieve (max 5000)",
                        "name": "tail",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.AppLogsResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/deployments/{id}/build-logs": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve build logs for a specific deployment",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Deployments"
                ],
                "summary": "Get deployment build logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Deployment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.BuildLogsResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API is running",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/httpapi.HealthResponse"
                        }
                    }
                }
            }
        },
        "/platform/analytics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get system-wide metrics for admin/monitoring dashboard",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Platform"
                ],
                "summary": "Get platform analytics",
                "responses": {
                    "200": {
                        "description": "Platform analytics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/platform/workers/{id}/analytics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get analytics for a specific worker node",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Platform"
                ],
                "summary": "Get worker analytics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Worker ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Worker analytics",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/workers": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get list of all worker nodes",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Platform"
                ],
                "summary": "List workers",
                "responses": {
                    "200": {
                        "description": "List of workers",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/httpapi.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.DeploymentDetails": {
            "type": "object",
            "properties": {
                "deployment": {
                    "$ref": "#/definitions/domain.DeploymentRecord"
                },
                "metrics": {
                    "$ref": "#/definitions/domain.DeploymentMetrics"
                },
                "pods": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.PodMetrics"
                    }
                },
                "resources": {
                    "$ref": "#/definitions/domain.ResourceAllocation"
                },
                "scaling": {
                    "$ref": "#/definitions/domain.ScalingInfo"
                }
            }
        },
        "domain.DeploymentMetrics": {
            "type": "object",
            "properties": {
                "bandwidth_received_bytes": {
                    "type": "integer"
                },
                "bandwidth_sent_bytes": {
                    "type": "integer"
                },
                "cpu_usage_percent": {
                    "type": "number"
                },
                "current_pods": {
                    "type": "integer"
                },
                "deployment_id": {
                    "type": "string"
                },
                "desired_pods": {
                    "type": "integer"
                },
                "last_updated": {
                    "type": "string"
                },
                "latency_p50_ms": {
                    "type": "number"
                },
                "latency_p90_ms": {
                    "type": "number"
                },
                "latency_p99_ms": {
                    "type": "number"
                },
                "memory_usage_mb": {
                    "type": "number"
                },
                "request_count_1h": {
                    "type": "integer"
                },
                "request_count_24h": {
                    "type": "integer"
                },
                "request_count_total": {
                    "type": "integer"
                },
                "requests_per_second": {
                    "type": "number"
                }
            }
        },
        "domain.DeploymentRecord": {
            "type": "object",
            "properties": {
                "build_args": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "build_logs": {
                    "type": "string"
                },
                "container": {
                    "type": "string"
                },
                "cpu_cores": {
                    "type": "number"
                },
                "cpu_limit_milli": {
                    "type": "integer"
                },
                "cpu_request_milli": {
                    "type": "integer"
                },
                "cpu_target_utilization": {
                    "type": "integer"
                },
                "deployment_id": {
                    "type": "string"
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                },
                "finished_at": {
                    "type": "string"
                },
                "image": {
                    "type": "string"
                },
                "max_replicas": {
                    "type": "integer"
                },
                "memory_mb": {
                    "type": "integer"
                },
                "min_replicas": {
                    "type": "integer"
                },
                "node_selector": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "package": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "repo": {
                    "type": "string"
                },
                "requested_by": {
                    "type": "string"
                },
                "scaling_mode": {
                    "type": "string"
                },
                "started_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "subdomain": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "domain.PodMetrics": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "e.g., \"2h30m\"",
                    "type": "string"
                },
                "cpu_usage_milli": {
                    "description": "Current CPU usage in millicores",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "memory_usage_mb": {
                    "description": "Current memory usage in MB",
                    "type": "number"
                },
                "pod_name": {
                    "type": "string"
                },
                "ready": {
                    "type": "boolean"
                },
                "restarts": {
                    "type": "integer"
                },
                "status": {
                    "description": "Running, Pending, Failed, etc.",
                    "type": "string"
                }
            }
        },
        "domain.ResourceAllocation": {
            "type": "object",
            "properties": {
                "cpu_limit_milli": {
                    "type": "integer"
                },
                "cpu_requested_milli": {
                    "type": "integer"
                },
                "cpu_usage_milli": {
                    "type": "integer"
                },
                "cpu_usage_percent": {
                    "description": "vs requested",
                    "type": "number"
                },
                "memory_limit_mb": {
                    "type": "integer"
                },
                "memory_requested_mb": {
                    "type": "integer"
                },
                "memory_usage_mb": {
                    "type": "number"
                },
                "memory_usage_percent": {
                    "description": "vs requested",
                    "type": "number"
                }
            }
        },
        "domain.ScalingInfo": {
            "type": "object",
            "properties": {
                "cpu_target_utilization": {
                    "type": "integer"
                },
                "current_pods": {
                    "type": "integer"
                },
                "desired_pods": {
                    "type": "integer"
                },
                "hpa_enabled": {
                    "type": "boolean"
                },
                "max_replicas": {
                    "type": "integer"
                },
                "min_replicas": {
                    "type": "integer"
                },
                "mode": {
                    "description": "\"none\", \"horizontal\"",
                    "type": "string"
                }
            }
        },
        "httpapi.AppLogsResponse": {
            "type": "object",
            "properties": {
                "application_logs": {
                    "type": "string",
                    "example": "Server listening on port 3000..."
                },
                "container": {
                    "type": "string",
                    "example": "myapp-container"
                },
                "deployment_id": {
                    "type": "string",
                    "example": "dep-123456"
                },
                "tail": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "httpapi.BatchDeploymentRequestPayload": {
            "type": "object",
            "required": [
                "requests"
            ],
            "properties": {
                "requests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.DeploymentRequestPayload"
                    }
                }
            }
        },
        "httpapi.BuildLogsResponse": {
            "type": "object",
            "properties": {
                "build_logs": {
                    "type": "string",
                    "example": "Step 1/5 : FROM node:18..."
                },
                "deployment_id": {
                    "type": "string",
                    "example": "dep-123456"
                },
                "status": {
                    "type": "string",
                    "example": "building"
                }
            }
        },
        "httpapi.DeployRequestPayload": {
            "type": "object",
            "required": [
                "repo"
            ],
            "properties": {
                "build_args": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "cpu_cores": {
                    "type": "number",
                    "example": 0.5
                },
                "cpu_limit_milli": {
                    "type": "integer",
                    "example": 1000
                },
                "cpu_request_milli": {
                    "type": "integer",
                    "example": 500
                },
                "cpu_target_utilization": {
                    "type": "integer",
                    "example": 70
                },
                "env": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "max_replicas": {
                    "type": "integer",
                    "example": 3
                },
                "memory_mb": {
                    "type": "integer",
                    "example": 512
                },
                "min_replicas": {
                    "type": "integer",
                    "example": 1
                },
                "node_selector": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "package": {
                    "description": "small, medium, large",
                    "type": "string",
                    "example": "small"
                },
                "port": {
                    "type": "integer",
                    "example": 3000
                },
                "repo": {
                    "type": "string",
                    "example": "https://github.com/user/repo"
                },
                "scaling_mode": {
                    "description": "Advanced options (optional - overridden by package if subscriber)",
                    "type": "string",
                    "example": "horizontal"
                },
                "subdomain": {
                    "description": "Optional - auto-generated if empty",
                    "type": "string",
                    "example": "myapp"
                }
            }
        },
        "httpapi.DeployResponse": {
            "type": "object",
            "properties": {
                "autoscaling_enabled": {
                    "type": "boolean",
                    "example": true
                },
                "cpu_cores": {
                    "type": "number",
                    "example": 0.5
                },
                "cpu_target_utilization": {
                    "type": "integer",
                    "example": 70
                },
                "deployment_id": {
                    "type": "string",
                    "example": "dep-123456"
                },
                "max_replicas": {
                    "type": "integer",
                    "example": 3
                },
                "memory_mb": {
                    "type": "integer",
                    "example": 512
                },
                "message": {
                    "type": "string",
                    "example": "deployment queued"
                },
                "min_replicas": {
                    "type": "integer",
                    "example": 1
                },
                "package": {
                    "type": "string",
                    "example": "small"
                },
                "port": {
                    "type": "integer",
                    "example": 3000
                },
                "repo": {
                    "type": "string",
                    "example": "https://github.com/user/repo"
                },
                "scaling_mode": {
                    "type": "string",
                    "example": "horizontal"
                },
                "status": {
                    "type": "string",
                    "example": "pending"
                },
                "subdomain": {
                    "type": "string",
                    "example": "myapp"
                },
                "url": {
                    "type": "string",
                    "example": "https://myapp.keshavstack.tech"
                }
            }
        },
        "httpapi.DeploymentInfo": {
            "type": "object",
            "properties": {
                "deployment_id": {
                    "type": "string",
                    "example": "dep-123456"
                },
                "package": {
                    "type": "string",
                    "example": "small"
                },
                "port": {
                    "type": "integer",
                    "example": 3000
                },
                "repo": {
                    "type": "string",
                    "example": "https://github.com/user/repo"
                },
                "scaling_mode": {
                    "type": "string",
                    "example": "horizontal"
                },
                "status": {
                    "type": "string",
                    "example": "running"
                },
                "subdomain": {
                    "type": "string",
                    "example": "myapp"
                }
            }
        },
        "httpapi.DeploymentListResponse": {
            "type": "object",
            "properties": {
                "deployments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httpapi.DeploymentInfo"
                    }
                }
            }
        },
        "httpapi.DeploymentRequestPayload": {
            "type": "object",
            "properties": {
                "bytes_received": {
                    "type": "integer"
                },
                "bytes_sent": {
                    "type": "integer"
                },
                "deployment_id": {
                    "description": "UUID or subdomain",
                    "type": "string"
                },
                "latency_ms": {
                    "type": "number"
                },
                "method": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "status_code": {
                    "type": "integer"
                },
                "timestamp": {
                    "description": "ISO 8601 format, optional",
                    "type": "string"
                }
            }
        },
        "httpapi.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Invalid request"
                }
            }
        },
        "httpapi.HealthResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "LaptopCloud running"
                }
            }
        },
        "httpapi.WhoAmIResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "provider": {
                    "type": "string",
                    "example": "github"
                },
                "sub": {
                    "type": "string",
                    "example": "user123"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Enter your JWT token in the format: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "MeshVPN Control Plane API",
	Description:      "API for deploying and managing applications on MeshVPN platform\nThis API provides endpoints for deploying applications, managing deployments, viewing logs, and monitoring analytics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
