services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token "$CLOUDFLARE_TUNNEL_TOKEN"
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
    network_mode: host
    restart: unless-stopped
